title: Saurabh Chalke's home on the Internet
description: "Hello! I'm Saurabh Chalke, your friendly neighborhood cypherpunk."
author:
  name: "Saurabh Chalke"
  email: "saurabh@zkHub.dev"
  url: "https://chalke.xyz/"

baseurl: /

google_analytics: G-5ME1WNF73X

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Saurabh Chalke"
year : "2023"
